/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_YappiWindow (void)
{
  GtkWidget *YappiWindow;
  GtkWidget *vbox2;
  GtkWidget *hbox4;
  GtkWidget *vbox4;
  GtkWidget *hbox5;
  GtkWidget *CommandLabel1;
  GtkWidget *InputBox;
  GtkWidget *OkButton;
  GtkWidget *handlebox1;
  GtkWidget *toolbar4;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *PlayBt;
  GtkWidget *StopBt;
  GtkWidget *scrollBt;
  GtkWidget *tmp_image;
  GtkWidget *MaximazeBt;
  GtkWidget *textview1;
  GtkWidget *statusbar1;

  YappiWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (YappiWindow), _("Yappi !"));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (YappiWindow), vbox2);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox4, FALSE, FALSE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox4, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, TRUE, FALSE, 0);

  CommandLabel1 = gtk_label_new (_(" CODE: "));
  gtk_widget_show (CommandLabel1);
  gtk_box_pack_start (GTK_BOX (hbox5), CommandLabel1, TRUE, TRUE, 0);

  InputBox = gtk_entry_new ();
  gtk_widget_show (InputBox);
  gtk_box_pack_start (GTK_BOX (hbox5), InputBox, TRUE, TRUE, 0);
  gtk_widget_set_size_request (InputBox, 115, -1);
  gtk_entry_set_text (GTK_ENTRY (InputBox), _("PRUEBA"));
  gtk_entry_set_activates_default (GTK_ENTRY (InputBox), TRUE);

  OkButton = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (OkButton);
  gtk_box_pack_start (GTK_BOX (hbox5), OkButton, TRUE, TRUE, 0);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (hbox4), handlebox1, TRUE, TRUE, 0);

  toolbar4 = gtk_toolbar_new ();
  gtk_widget_show (toolbar4);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar4);
  gtk_widget_set_size_request (toolbar4, 209, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar4), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar4));

  PlayBt = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-media-play");
  gtk_widget_show (PlayBt);
  gtk_container_add (GTK_CONTAINER (toolbar4), PlayBt);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (PlayBt), TRUE);

  StopBt = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-media-pause");
  gtk_widget_show (StopBt);
  gtk_container_add (GTK_CONTAINER (toolbar4), StopBt);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (StopBt), TRUE);

  scrollBt = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-go-down");
  gtk_widget_show (scrollBt);
  gtk_container_add (GTK_CONTAINER (toolbar4), scrollBt);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (scrollBt), TRUE);

  tmp_image = gtk_image_new_from_stock ("gtk-zoom-in", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  MaximazeBt = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (MaximazeBt);
  gtk_container_add (GTK_CONTAINER (toolbar4), MaximazeBt);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (MaximazeBt), TRUE);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_box_pack_start (GTK_BOX (vbox2), textview1, TRUE, TRUE, 1);
  gtk_widget_set_size_request (textview1, 136, 87);
  gtk_container_set_border_width (GTK_CONTAINER (textview1), 5);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox2), statusbar1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) InputBox, "activate",
                    G_CALLBACK (on_InputBox_activate),
                    NULL);
  g_signal_connect ((gpointer) InputBox, "grab_focus",
                    G_CALLBACK (InputBox_grab_focus),
                    NULL);
  g_signal_connect ((gpointer) OkButton, "button_press_event",
                    G_CALLBACK (on_OkButton_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (YappiWindow, YappiWindow, "YappiWindow");
  GLADE_HOOKUP_OBJECT (YappiWindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (YappiWindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (YappiWindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (YappiWindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (YappiWindow, CommandLabel1, "CommandLabel1");
  GLADE_HOOKUP_OBJECT (YappiWindow, InputBox, "InputBox");
  GLADE_HOOKUP_OBJECT (YappiWindow, OkButton, "OkButton");
  GLADE_HOOKUP_OBJECT (YappiWindow, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (YappiWindow, toolbar4, "toolbar4");
  GLADE_HOOKUP_OBJECT (YappiWindow, PlayBt, "PlayBt");
  GLADE_HOOKUP_OBJECT (YappiWindow, StopBt, "StopBt");
  GLADE_HOOKUP_OBJECT (YappiWindow, scrollBt, "scrollBt");
  GLADE_HOOKUP_OBJECT (YappiWindow, MaximazeBt, "MaximazeBt");
  GLADE_HOOKUP_OBJECT (YappiWindow, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (YappiWindow, statusbar1, "statusbar1");

  return YappiWindow;
}

